package eth.likespro.commons.models

enum class Status {
    SUCCESS, ERROR_UNKNOWN, ERROR_MAINTENANCE, ERROR_INVALID_SESSION, ERROR_INVALID_SIGNATURE, ERROR_INVALID_TIMESTAMP, ERROR_UNKNOWN_METHOD, ERROR_USED_KEY, ERROR_USED_PEER_ID, ERROR_FILE_NOT_FOUND, ERROR_HOSTING_NOT_RESPONDS, ERROR_FILE_HAVE_NO_SOURCES, ERROR_FILE_HAVE_NO_VALID_SOURCES, ERROR_NO_AGENTS, ERROR_CANNOT_DOWNLOAD_FOLDER, ERROR_SHA256_DOES_NOT_MATCH, ERROR_INVALID_PATH, ERROR_INSUFFICIENT_SPACE, ERROR_USED_PATH, ERROR_BUSY_STORAGES, ERROR_SERVER_IS_BUSY, ERROR_FOLDER_DOES_NOT_EXIST, FILE_SIZE_DOES_NOT_MATCH
}